version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://13.233.162.1/api/v1
      - ACCESS_JWT_SECRET=access
      - ACCESS_TOKEN_LIFE=7d
      - REFRESH_TOKEN_SECRET=refresh
      - REFRESH_TOKEN_LIFE=7d
      - NEXT_PUBLIC_IMAGE_URL=http://13.233.162.1
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://panel_owner:3mpqUCdeBH1V@ep-snowy-cherry-a1cz7rty.ap-southeast-1.aws.neon.tech/backend?sslmode=require
      - PORT=4000
      - CORS_ORIGIN=http://13.233.162.1
      - ACCESS_JWT_SECRET=access
      - ACCESS_TOKEN_LIFE=7d
      - REFRESH_TOKEN_SECRET=refresh
      - REFRESH_TOKEN_LIFE=7d
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server
