name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create ENV Files
        run: |
          echo "module.exports = { apps: [{ name: 'backend', script: 'index.js', env: { PORT: 4000, CORS_ORIGIN: '${{ secrets.CORS_ORIGIN }}', ACCESS_JWT_SECRET: '${{ secrets.ACCESS_JWT_SECRET }}', DATABASE_URL: '${{ secrets.DATABASE_URL }}' } }] }" > server/ecosystem.config.js

          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > client/.env

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/Xcel-B2B
            git pull
            cd server
            npm install
            pm2 restart backend
            cd ../client
            npm install
            npm run build
            pm2 restart frontend
