name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          command_timeout: "30m"
          envs: GITHUB_SHA
          script: |
            # Navigate to project directory
            cd /home/ec2-user/Xcel-B2B

            # Backup existing .env files
            cp server/.env server/.env.backup
            cp client/.env client/.env.backup

            # Fetch latest changes
            git fetch --all
            git reset --hard origin/main

            # Restore .env files
            mv server/.env.backup server/.env
            mv client/.env.backup client/.env

            # Backend setup
            cd server
            npm ci
            npx prisma generate

            # Frontend setup
            cd ../client
            npm ci
            npm run build

            # Restart PM2 processes
            cd ..
            pm2 restart backend
            pm2 restart frontend
            pm2 save
