name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create ecosystem.config.js
        run: |
          echo "module.exports = { 
            apps: [
              { 
                name: 'backend',
                script: 'index.js',
                env: { 
                  PORT: 4000,
                  CORS_ORIGIN: '${{ secrets.CORS_ORIGIN }}',
                  ACCESS_JWT_SECRET: '${{ secrets.ACCESS_JWT_SECRET }}',
                  DATABASE_URL: '${{ secrets.DATABASE_URL }}'
                }
              }
            ]
          }" > server/ecosystem.config.js

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: "20m"
          script: |
            # Navigate to project directory
            cd /home/ec2-user/Xcel-B2B

            # Backup current env files
            cp server/.env server/.env.backup || true
            cp client/.env client/.env.backup || true
            cp server/ecosystem.config.js server/ecosystem.config.js.backup || true

            # Pull latest changes
            git stash
            git pull origin main

            # Restore env files
            mv server/.env.backup server/.env
            mv client/.env.backup client/.env
            mv server/ecosystem.config.js.backup server/ecosystem.config.js

            # Backend deployment
            cd server
            npm install
            npx prisma generate
            pm2 restart backend || pm2 start index.js --name backend

            # Frontend deployment
            cd ../client
            npm install
            npm run build
            pm2 restart frontend || pm2 start npm --name frontend -- start

            # Save PM2 configuration
            pm2 save
