name: Docker Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ec2-user
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            # Reload shell to ensure docker group is loaded
            source ~/.bashrc &&
            cd /home/ec2-user/app &&
            git pull &&
            # Use full path for docker-compose
            /usr/local/bin/docker-compose down &&
            /usr/local/bin/docker-compose build --no-cache &&
            /usr/local/bin/docker-compose up -d
          '
